---
title: Simon Yost
tag: Leader, Learner, Speaker<br/>Cloud DevOps, Digital Products, Web Services
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Simon's site.
keywords: Simon, Yost, siyo, leader, technology, consultant, ux, ui, engineer, engineering, teams, multidisciplinary
#baseurl: "/" #remote
baseurl: "" #local
url: http://simonyost.com
img_path: "/static/assets/img/blog"
author:
  name: Simon Yost
  first_name: Simon
  last_name: Yost
  avatar: "/static/assets/img/landing/avatar.jpg"
  github_username: simonyost
  youtube_link: https://www.youtube.com/playlist?list=PLtCAcUB3FyCj6AgSWrcqa3HBC-M2oKmWw
  instagram_id: simon.yost
  linkedin_id: simonyost
  email: simonyost@gmail.com
  # cv: "/static/assets/docs/SimonYost_Resume_2018.pdf"
  skill_icon1:
  - name: fa-heart
  - name: fa-cloud
  skill_icon2:
  - name: fa-dashboard
  - name: fa-sitemap
  desc: "<h3>I help teams create digital products and experiences that connect people.</h3>
  <p>While specializing in maximizing the potential of multi-disciplinary teams, I create sustainable and digital products on cloud infrastructure.</p>
  <p>I have spent 15 years building organizations (startups, nonprofits, and enterprise) in the Midwest region by spearheading technology strategy and software products. That includes countless hours coaching professionals and students on building applications, creating digital products, and installing systems in businesses.
  I currently serve as a technology enablement consultant at Slalom St. Louis.</p>
  <p>Outside of work, I am a husband, father, amateur cyclist, and self-professed coffee aficionado. My passions include foster/adopt parenting and Nebraska football.</p>"
disqus: 
ga:
  id: UA-113489820-1
go: 
gio: 
donation: false
index_carousel: true
blog_carousel: true
sass:
  style: compressed
encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
