---
title: Simon Yost
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Simon's site.
keywords: Simon, Yost, siyo, Leader, Technology
baseurl: "/"
url: http://simonyost.com
img_path: "/static/assets/img/blog"
author:
  name: Simon Yost
  first_name: Simon
  last_name: Yost
  avatar: "/static/assets/img/landing/avatar.jpg"
  github_username: simonyost
  linkedin_id: simonyost
  facebook_username: simonyost
  twitter_username: simonyost
  email: simonyost@gmail.com
  cv: "/static/assets/docs/SimonYost_Resume_2018.pdf"
  skill_icon1:
  - name: fa-heart
  - name: fa-cloud
  skill_icon2:
  - name: fa-dashboard
  - name: fa-sitemap
  desc: "<p>Simon Yost is a product creator and team leader. He specializes in maximizing the potential of multi-disciplinary teams through creating sustainable and nimble web applications. Simon has spent 15 years building startup businesses and nonprofit organization in the Midwest region by spearheading digital strategy and content delivery. He has spent countless hours coaching professionals and students on building web applications, creating digital strategies, and installing systems in their businesses. Simon brought his knowledge to the classroom and taught web development at Washington University in St. Louis. He currently serves as a technology consultant at Slalom and as Founder of Simply Done, a modern home repair and management service.</p>
  <p>Outside of work, Simon is a husband, father, amateur cyclist, and self-professed coffee aficionado. His passions include work as foster/adopt parent and Nebraska football.</p>"
disqus: 
ga:
  id: UA-113489820-1
go: 
gio: 
donation: false
index_carousel: true
blog_carousel: true
sass:
  style: compressed
encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
