---
title: Simon Yost
tag: Leader, Learner, Speaker<br/>Cloud DevOps, Digital Products, Web Services
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Simon Yost
keywords: Simon, Yost, siyo, leader, technology, consultant, ux, ui, engineer, engineering, teams, multidisciplinary
#baseurl: "/" #remote
baseurl: "" #local
url: http://simonyost.com
img_path: "/static/assets/img/blog"
author:
  name: Simon Yost
  first_name: Simon
  last_name: Yost
  avatar: "/static/assets/img/landing/avatar.jpg"
  github_username: simonyost
  youtube_link: https://www.youtube.com/playlist?list=PLtCAcUB3FyCj6AgSWrcqa3HBC-M2oKmWw
  instagram_id: simon.yost
  linkedin_id: simonyost
  email: simonyost@gmail.com
  # cv: "/static/assets/docs/SimonYost_Resume_2018.pdf"
  skill_icon1:
  - name: fa-heart
  - name: fa-cloud
  skill_icon2:
  - name: fa-dashboard
  - name: fa-sitemap
  desc: "<h3>I am all about tribes thriving.</h3>
  <p>I am a husband, father, technology leader, podcast host, amateur cyclist, and <br>self-professed coffee aficionado.
  <br>My passions include foster/adopt parenting and Nebraska football.</p>"
disqus: 
ga:
  id: UA-113489820-1
go: 
gio: 
donation: false
index_carousel: true
blog_carousel: true
sass:
  style: compressed
encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
