---
title: Simon Yost
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Simon's site.
keywords: Simon, Yost, siyo, Leader, Technology
baseurl: "/"
url: http://simonyost.com
img_path: "/static/assets/img/blog"
author:
  name: Simon Yost
  first_name: Simon
  last_name: Yost
  avatar: "/static/assets/img/landing/avatar.jpg"
  github_username: simonyost
  linkedin_id: simonyost
  facebook_username: simonyost
  twitter_username: simonyost
  email: simonyost@gmail.com
  cv: "/static/assets/docs/SimonYost_Resume_2018.pdf"
  skill_icon1:
  - name: fa-heart
  - name: fa-cloud
  skill_icon2:
  - name: fa-dashboard
  - name: fa-sitemap
  desc: I am a Product Manager & Team Leader that creates products and specializes
    in maximizing the potential of teams. My focus is leading teams to create sustainable
    and nimble digital applications so people can focus on other people.
disqus: 
ga:
  id: UA-113489820-1
go: 
gio: 
donation: false
index_carousel: true
blog_carousel: true
sass:
  style: compressed
encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
